# Generated by Django 3.2.15 on 2022-09-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='comment',
            field=models.TextField(verbose_name='Açıklama sütunu'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Eposta Adresi'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserve.shop', verbose_name='Rezervasyon Tarihi'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_num',
            field=models.IntegerField(default=1, verbose_name='Rezervasyon Yapan Kişi Sayısı'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_time',
            field=models.TimeField(verbose_name='Rezervasyon Zamanı'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='end_time',
            field=models.TimeField(verbose_name='Kapanış Saati'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='max_reserve_num',
            field=models.IntegerField(verbose_name=' Saat Başına Kişi Sayısı'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='reservable_date',
            field=models.IntegerField(verbose_name='Rezervasyon müsait Tarihi'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_time',
            field=models.TimeField(verbose_name='Açılış Saatleri'),
        ),
    ]
