# Generated by Django 3.2.15 on 2022-09-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20220927_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_date',
            field=models.CharField(choices=[('', 'Rezervasyon Tarihi'), (1, '6/1'), (2, '6/2'), (3, '6/3')], max_length=20, verbose_name='予約日'),
        ),
    ]
